	version: 2.1

	orbs:
	 win: circleci/windows@2.2.0

	jobs:
	 build:
	  executor: win/default     

	 steps:	
	  - checkout
	  - run
	   name: Navigate to solution folder and build the solution
	   command: cd UnitTestingAndMockingUsingXUnitAndMoq | dotnet 	