version: 2.1

orbs:
 win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default    
    steps:
      - checkout:
          path: C:\Users\circleci\project
      - run:
          name: "Navigate to the UnitTestingAndMockingUsingXUnitAndMoq solution dir"
          command: cd UnitTestingAndMockingUsingXUnitAndMoq
      - run:
          name: "Install project dependencies"
          command: dotnet restore
      - run:
          name: "Run Build step"
          command: msbuild
